name: conectimovel_app
description: "Aplicativo para conectar compradores e corretores."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

  http: ^1.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  image_picker: ^1.1.1
  introduction_screen: ^3.1.12 
  rive: ^0.13.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_splash.png



flutter:
  uses-material-design: true
  fonts:
  - family: PlayfairDisplay
    fonts:
      - asset: assets/fonts/PlayfairDisplay-Regular.ttf
      - asset: assets/fonts/PlayfairDisplay-Bold.ttf
        weight: 700
  assets:
    - assets/images/
    - assets/rive/
