name: conectimovel_app
description: "Aplicativo para conectar compradores e corretores."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  introduction_screen: ^3.1.12 # NOVO
  shared_preferences: ^2.2.3 # NOVO

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/